- name: Build image
  docker_image:
    path: ../docker/
    name: "{{ image }}"

- name: get  docker  aws login
  shell: aws ecr get-login --region {{ awsregion }}
  register: login

- name: get repos
  shell: aws ecr describe-repositories
  register: repos

- name: set fact
  set_fact:
    repos: "{{repos.stdout}}"

- name: debugging
  debug:
    var : "{{ repos.repositories | selectattr('repositoryName', 'echoserver') }}"

- name: create repo
  shell:  aws ecr create-repository --repository-name {{ ecrRepoName }}
  when:    repos.repositories|length ==  0 or   repos.repositories.0.repositoryName!= "{{ecrRepoName }}"
- name: push image
  docker_image:
    name: "{{ image }}"
    repository: "{{ ecrImage }}"
    state: present
    push: true
    #shell: docker push  {{ ecrImage }}


- name: Remove echoserver image
  docker_image:
    name: "{{ image }}"
    state: absent


- name: Remove ecr  image locally
  docker_image:
    name: "{{ ecrImage }}"
    state: absent
