- name: Build image
  docker_image:
    path: ../docker/
    name: "{{ image }}"

- name: get  docker  aws login
  shell: aws ecr get-login --region {{ awsregion }}
  register: login
  changed_when: false

- name: execute login
  shell: "{{ login.stdout }}"
  changed_when: false

- name: get repos
  shell: aws ecr describe-repositories --region {{ awsregion }}
  register: repos

- name: create repo
  shell:  aws ecr create-repository  --region {{ awsregion }} --repository-name {{ ecrRepoName }}
  when:  "ecrRepoName not in repos.stdout"   #repos.repositories|length ==  0 or   repos.repositories.0.repositoryName!= "{{ecrRepoName }}"

- name: push image
  docker_image:
    name: "{{ image }}"
    repository: "{{ ecrImage }}"
    tag: "{{ image }} {{ ecrImage }}"
    state: present
    push: true


- name: Remove echoserver image
  docker_image:
    name: "{{ image }}"
    state: absent


- name: Remove ecr  image locally
  docker_image:
    name: "{{ ecrImage }}"
    state: absent
