
---
- name: include vars 
  include_vars: 
    file: ../../../files/container.json


- name: Create task definition
  ecs_taskdefinition:
    containers: "{{  containers }}" 
    family: echoserver
    state: present

- name: Run task
  ecs_task:
    operation: run
    cluster: "{{ ecs_cluster }}"
    task_definition: echoserver 
    count: 1
    started_by: ec2-user
